name = "ucolorr"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

services = [
  { binding = "UCOLORR", service = "ucolorr" },
]

[vars]
CF_PAGES_URL="http://localhost:5173"
CONTACT_EMAIL_RECIPIENT="dev@ucolorr.app"
