/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _CfMETADATA {
  key: Generated<number | null>;
  value: Buffer | null;
}

export interface Color {
  colorSpace: string;
  id: Generated<number>;
  jsonComponents: string;
  userId: number;
}

export interface D1Migrations {
  appliedAt: Generated<string>;
  id: Generated<number | null>;
  name: string | null;
}

export interface Otp {
  code: string;
  email: string;
  validity: string;
}

export interface Palette {
  id: Generated<number>;
  jsonColors: string;
  jsonGenerator: string;
  userId: number;
}

export interface User {
  email: string;
  firstName: string;
  id: Generated<number>;
  lastName: string;
  role: string;
}

export interface DB {
  _CfMETADATA: _CfMETADATA;
  color: Color;
  d1Migrations: D1Migrations;
  otp: Otp;
  palette: Palette;
  user: User;
}
