/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../../routes/__root'
import { Route as AdminImport } from './../../routes/admin'
import { Route as PublicImport } from './../../routes/_public'
import { Route as IndexImport } from './../../routes/index'
import { Route as AdminIndexImport } from './../../routes/admin/index'
import { Route as AdminPublicPalettesImport } from './../../routes/admin/public-palettes'
import { Route as AuthSignUpIndexImport } from './../../routes/auth/sign-up/index'
import { Route as AuthSignInIndexImport } from './../../routes/auth/sign-in/index'
import { Route as AdminUsersIndexImport } from './../../routes/admin/users/index'
import { Route as AdminPublicPalettesIndexImport } from './../../routes/admin/public-palettes/index'
import { Route as PublicScalePaletteIndexImport } from './../../routes/_public/scale-palette/index'
import { Route as PublicRandomPaletteIndexImport } from './../../routes/_public/random-palette/index'
import { Route as PublicPalettesExplorerIndexImport } from './../../routes/_public/palettes-explorer/index'
import { Route as PublicPaletteEditorIndexImport } from './../../routes/_public/palette-editor/index'
import { Route as PublicMyPalettesIndexImport } from './../../routes/_public/my-palettes/index'
import { Route as PublicImagePickerIndexImport } from './../../routes/_public/image-picker/index'
import { Route as PublicHarmonyPaletteIndexImport } from './../../routes/_public/harmony-palette/index'
import { Route as PublicContrastCheckerIndexImport } from './../../routes/_public/contrast-checker/index'
import { Route as PublicContactIndexImport } from './../../routes/_public/contact/index'
import { Route as AdminPublicPalettesGenerateIndexImport } from './../../routes/admin/public-palettes/generate/index'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminPublicPalettesRoute = AdminPublicPalettesImport.update({
  id: '/public-palettes',
  path: '/public-palettes',
  getParentRoute: () => AdminRoute,
} as any)

const AuthSignUpIndexRoute = AuthSignUpIndexImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInIndexRoute = AuthSignInIndexImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminPublicPalettesIndexRoute = AdminPublicPalettesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPublicPalettesRoute,
} as any)

const PublicScalePaletteIndexRoute = PublicScalePaletteIndexImport.update({
  id: '/scale-palette/',
  path: '/scale-palette/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicRandomPaletteIndexRoute = PublicRandomPaletteIndexImport.update({
  id: '/random-palette/',
  path: '/random-palette/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicPalettesExplorerIndexRoute =
  PublicPalettesExplorerIndexImport.update({
    id: '/palettes-explorer/',
    path: '/palettes-explorer/',
    getParentRoute: () => PublicRoute,
  } as any)

const PublicPaletteEditorIndexRoute = PublicPaletteEditorIndexImport.update({
  id: '/palette-editor/',
  path: '/palette-editor/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicMyPalettesIndexRoute = PublicMyPalettesIndexImport.update({
  id: '/my-palettes/',
  path: '/my-palettes/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicImagePickerIndexRoute = PublicImagePickerIndexImport.update({
  id: '/image-picker/',
  path: '/image-picker/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicHarmonyPaletteIndexRoute = PublicHarmonyPaletteIndexImport.update({
  id: '/harmony-palette/',
  path: '/harmony-palette/',
  getParentRoute: () => PublicRoute,
} as any)

const PublicContrastCheckerIndexRoute = PublicContrastCheckerIndexImport.update(
  {
    id: '/contrast-checker/',
    path: '/contrast-checker/',
    getParentRoute: () => PublicRoute,
  } as any,
)

const PublicContactIndexRoute = PublicContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRoute,
} as any)

const AdminPublicPalettesGenerateIndexRoute =
  AdminPublicPalettesGenerateIndexImport.update({
    id: '/generate/',
    path: '/generate/',
    getParentRoute: () => AdminPublicPalettesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/public-palettes': {
      id: '/admin/public-palettes'
      path: '/public-palettes'
      fullPath: '/admin/public-palettes'
      preLoaderRoute: typeof AdminPublicPalettesImport
      parentRoute: typeof AdminImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_public/contact/': {
      id: '/_public/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/contrast-checker/': {
      id: '/_public/contrast-checker/'
      path: '/contrast-checker'
      fullPath: '/contrast-checker'
      preLoaderRoute: typeof PublicContrastCheckerIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/harmony-palette/': {
      id: '/_public/harmony-palette/'
      path: '/harmony-palette'
      fullPath: '/harmony-palette'
      preLoaderRoute: typeof PublicHarmonyPaletteIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/image-picker/': {
      id: '/_public/image-picker/'
      path: '/image-picker'
      fullPath: '/image-picker'
      preLoaderRoute: typeof PublicImagePickerIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/my-palettes/': {
      id: '/_public/my-palettes/'
      path: '/my-palettes'
      fullPath: '/my-palettes'
      preLoaderRoute: typeof PublicMyPalettesIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/palette-editor/': {
      id: '/_public/palette-editor/'
      path: '/palette-editor'
      fullPath: '/palette-editor'
      preLoaderRoute: typeof PublicPaletteEditorIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/palettes-explorer/': {
      id: '/_public/palettes-explorer/'
      path: '/palettes-explorer'
      fullPath: '/palettes-explorer'
      preLoaderRoute: typeof PublicPalettesExplorerIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/random-palette/': {
      id: '/_public/random-palette/'
      path: '/random-palette'
      fullPath: '/random-palette'
      preLoaderRoute: typeof PublicRandomPaletteIndexImport
      parentRoute: typeof PublicImport
    }
    '/_public/scale-palette/': {
      id: '/_public/scale-palette/'
      path: '/scale-palette'
      fullPath: '/scale-palette'
      preLoaderRoute: typeof PublicScalePaletteIndexImport
      parentRoute: typeof PublicImport
    }
    '/admin/public-palettes/': {
      id: '/admin/public-palettes/'
      path: '/'
      fullPath: '/admin/public-palettes/'
      preLoaderRoute: typeof AdminPublicPalettesIndexImport
      parentRoute: typeof AdminPublicPalettesImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexImport
      parentRoute: typeof AdminImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/public-palettes/generate/': {
      id: '/admin/public-palettes/generate/'
      path: '/generate'
      fullPath: '/admin/public-palettes/generate'
      preLoaderRoute: typeof AdminPublicPalettesGenerateIndexImport
      parentRoute: typeof AdminPublicPalettesImport
    }
  }
}

// Create and export the route tree

interface PublicRouteChildren {
  PublicContactIndexRoute: typeof PublicContactIndexRoute
  PublicContrastCheckerIndexRoute: typeof PublicContrastCheckerIndexRoute
  PublicHarmonyPaletteIndexRoute: typeof PublicHarmonyPaletteIndexRoute
  PublicImagePickerIndexRoute: typeof PublicImagePickerIndexRoute
  PublicMyPalettesIndexRoute: typeof PublicMyPalettesIndexRoute
  PublicPaletteEditorIndexRoute: typeof PublicPaletteEditorIndexRoute
  PublicPalettesExplorerIndexRoute: typeof PublicPalettesExplorerIndexRoute
  PublicRandomPaletteIndexRoute: typeof PublicRandomPaletteIndexRoute
  PublicScalePaletteIndexRoute: typeof PublicScalePaletteIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicContrastCheckerIndexRoute: PublicContrastCheckerIndexRoute,
  PublicHarmonyPaletteIndexRoute: PublicHarmonyPaletteIndexRoute,
  PublicImagePickerIndexRoute: PublicImagePickerIndexRoute,
  PublicMyPalettesIndexRoute: PublicMyPalettesIndexRoute,
  PublicPaletteEditorIndexRoute: PublicPaletteEditorIndexRoute,
  PublicPalettesExplorerIndexRoute: PublicPalettesExplorerIndexRoute,
  PublicRandomPaletteIndexRoute: PublicRandomPaletteIndexRoute,
  PublicScalePaletteIndexRoute: PublicScalePaletteIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminPublicPalettesRouteChildren {
  AdminPublicPalettesIndexRoute: typeof AdminPublicPalettesIndexRoute
  AdminPublicPalettesGenerateIndexRoute: typeof AdminPublicPalettesGenerateIndexRoute
}

const AdminPublicPalettesRouteChildren: AdminPublicPalettesRouteChildren = {
  AdminPublicPalettesIndexRoute: AdminPublicPalettesIndexRoute,
  AdminPublicPalettesGenerateIndexRoute: AdminPublicPalettesGenerateIndexRoute,
}

const AdminPublicPalettesRouteWithChildren =
  AdminPublicPalettesRoute._addFileChildren(AdminPublicPalettesRouteChildren)

interface AdminRouteChildren {
  AdminPublicPalettesRoute: typeof AdminPublicPalettesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPublicPalettesRoute: AdminPublicPalettesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/public-palettes': typeof AdminPublicPalettesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/contrast-checker': typeof PublicContrastCheckerIndexRoute
  '/harmony-palette': typeof PublicHarmonyPaletteIndexRoute
  '/image-picker': typeof PublicImagePickerIndexRoute
  '/my-palettes': typeof PublicMyPalettesIndexRoute
  '/palette-editor': typeof PublicPaletteEditorIndexRoute
  '/palettes-explorer': typeof PublicPalettesExplorerIndexRoute
  '/random-palette': typeof PublicRandomPaletteIndexRoute
  '/scale-palette': typeof PublicScalePaletteIndexRoute
  '/admin/public-palettes/': typeof AdminPublicPalettesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/admin/public-palettes/generate': typeof AdminPublicPalettesGenerateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PublicRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/contrast-checker': typeof PublicContrastCheckerIndexRoute
  '/harmony-palette': typeof PublicHarmonyPaletteIndexRoute
  '/image-picker': typeof PublicImagePickerIndexRoute
  '/my-palettes': typeof PublicMyPalettesIndexRoute
  '/palette-editor': typeof PublicPaletteEditorIndexRoute
  '/palettes-explorer': typeof PublicPalettesExplorerIndexRoute
  '/random-palette': typeof PublicRandomPaletteIndexRoute
  '/scale-palette': typeof PublicScalePaletteIndexRoute
  '/admin/public-palettes': typeof AdminPublicPalettesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/admin/public-palettes/generate': typeof AdminPublicPalettesGenerateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/public-palettes': typeof AdminPublicPalettesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/_public/contact/': typeof PublicContactIndexRoute
  '/_public/contrast-checker/': typeof PublicContrastCheckerIndexRoute
  '/_public/harmony-palette/': typeof PublicHarmonyPaletteIndexRoute
  '/_public/image-picker/': typeof PublicImagePickerIndexRoute
  '/_public/my-palettes/': typeof PublicMyPalettesIndexRoute
  '/_public/palette-editor/': typeof PublicPaletteEditorIndexRoute
  '/_public/palettes-explorer/': typeof PublicPalettesExplorerIndexRoute
  '/_public/random-palette/': typeof PublicRandomPaletteIndexRoute
  '/_public/scale-palette/': typeof PublicScalePaletteIndexRoute
  '/admin/public-palettes/': typeof AdminPublicPalettesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/admin/public-palettes/generate/': typeof AdminPublicPalettesGenerateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/admin'
    | '/admin/public-palettes'
    | '/admin/'
    | '/contact'
    | '/contrast-checker'
    | '/harmony-palette'
    | '/image-picker'
    | '/my-palettes'
    | '/palette-editor'
    | '/palettes-explorer'
    | '/random-palette'
    | '/scale-palette'
    | '/admin/public-palettes/'
    | '/admin/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/public-palettes/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/admin'
    | '/contact'
    | '/contrast-checker'
    | '/harmony-palette'
    | '/image-picker'
    | '/my-palettes'
    | '/palette-editor'
    | '/palettes-explorer'
    | '/random-palette'
    | '/scale-palette'
    | '/admin/public-palettes'
    | '/admin/users'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/public-palettes/generate'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/admin'
    | '/admin/public-palettes'
    | '/admin/'
    | '/_public/contact/'
    | '/_public/contrast-checker/'
    | '/_public/harmony-palette/'
    | '/_public/image-picker/'
    | '/_public/my-palettes/'
    | '/_public/palette-editor/'
    | '/_public/palettes-explorer/'
    | '/_public/random-palette/'
    | '/_public/scale-palette/'
    | '/admin/public-palettes/'
    | '/admin/users/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/admin/public-palettes/generate/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_public",
        "/admin",
        "/auth/sign-in/",
        "/auth/sign-up/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/_public": {
      "filePath": "_public.ts",
      "children": [
        "/_public/contact/",
        "/_public/contrast-checker/",
        "/_public/harmony-palette/",
        "/_public/image-picker/",
        "/_public/my-palettes/",
        "/_public/palette-editor/",
        "/_public/palettes-explorer/",
        "/_public/random-palette/",
        "/_public/scale-palette/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/public-palettes",
        "/admin/",
        "/admin/users/"
      ]
    },
    "/admin/public-palettes": {
      "filePath": "admin/public-palettes.ts",
      "parent": "/admin",
      "children": [
        "/admin/public-palettes/",
        "/admin/public-palettes/generate/"
      ]
    },
    "/admin/": {
      "filePath": "admin/index.ts",
      "parent": "/admin"
    },
    "/_public/contact/": {
      "filePath": "_public/contact/index.ts",
      "parent": "/_public"
    },
    "/_public/contrast-checker/": {
      "filePath": "_public/contrast-checker/index.ts",
      "parent": "/_public"
    },
    "/_public/harmony-palette/": {
      "filePath": "_public/harmony-palette/index.ts",
      "parent": "/_public"
    },
    "/_public/image-picker/": {
      "filePath": "_public/image-picker/index.ts",
      "parent": "/_public"
    },
    "/_public/my-palettes/": {
      "filePath": "_public/my-palettes/index.tsx",
      "parent": "/_public"
    },
    "/_public/palette-editor/": {
      "filePath": "_public/palette-editor/index.tsx",
      "parent": "/_public"
    },
    "/_public/palettes-explorer/": {
      "filePath": "_public/palettes-explorer/index.tsx",
      "parent": "/_public"
    },
    "/_public/random-palette/": {
      "filePath": "_public/random-palette/index.ts",
      "parent": "/_public"
    },
    "/_public/scale-palette/": {
      "filePath": "_public/scale-palette/index.ts",
      "parent": "/_public"
    },
    "/admin/public-palettes/": {
      "filePath": "admin/public-palettes/index.tsx",
      "parent": "/admin/public-palettes"
    },
    "/admin/users/": {
      "filePath": "admin/users/index.tsx",
      "parent": "/admin"
    },
    "/auth/sign-in/": {
      "filePath": "auth/sign-in/index.tsx"
    },
    "/auth/sign-up/": {
      "filePath": "auth/sign-up/index.tsx"
    },
    "/admin/public-palettes/generate/": {
      "filePath": "admin/public-palettes/generate/index.ts",
      "parent": "/admin/public-palettes"
    }
  }
}
ROUTE_MANIFEST_END */
