/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ScalePaletteIndexImport } from './routes/scale-palette/index'
import { Route as RandomPaletteIndexImport } from './routes/random-palette/index'
import { Route as MyPalettesIndexImport } from './routes/my-palettes/index'
import { Route as ImagePickerIndexImport } from './routes/image-picker/index'
import { Route as HarmonyPaletteIndexImport } from './routes/harmony-palette/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthSignUpIndexImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexImport } from './routes/auth/sign-in/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ScalePaletteIndexRoute = ScalePaletteIndexImport.update({
  id: '/scale-palette/',
  path: '/scale-palette/',
  getParentRoute: () => rootRoute,
} as any)

const RandomPaletteIndexRoute = RandomPaletteIndexImport.update({
  id: '/random-palette/',
  path: '/random-palette/',
  getParentRoute: () => rootRoute,
} as any)

const MyPalettesIndexRoute = MyPalettesIndexImport.update({
  id: '/my-palettes/',
  path: '/my-palettes/',
  getParentRoute: () => rootRoute,
} as any)

const ImagePickerIndexRoute = ImagePickerIndexImport.update({
  id: '/image-picker/',
  path: '/image-picker/',
  getParentRoute: () => rootRoute,
} as any)

const HarmonyPaletteIndexRoute = HarmonyPaletteIndexImport.update({
  id: '/harmony-palette/',
  path: '/harmony-palette/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpIndexRoute = AuthSignUpIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignUpRoute,
} as any)

const AuthSignInIndexRoute = AuthSignInIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/harmony-palette/': {
      id: '/harmony-palette/'
      path: '/harmony-palette'
      fullPath: '/harmony-palette'
      preLoaderRoute: typeof HarmonyPaletteIndexImport
      parentRoute: typeof rootRoute
    }
    '/image-picker/': {
      id: '/image-picker/'
      path: '/image-picker'
      fullPath: '/image-picker'
      preLoaderRoute: typeof ImagePickerIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-palettes/': {
      id: '/my-palettes/'
      path: '/my-palettes'
      fullPath: '/my-palettes'
      preLoaderRoute: typeof MyPalettesIndexImport
      parentRoute: typeof rootRoute
    }
    '/random-palette/': {
      id: '/random-palette/'
      path: '/random-palette'
      fullPath: '/random-palette'
      preLoaderRoute: typeof RandomPaletteIndexImport
      parentRoute: typeof rootRoute
    }
    '/scale-palette/': {
      id: '/scale-palette/'
      path: '/scale-palette'
      fullPath: '/scale-palette'
      preLoaderRoute: typeof ScalePaletteIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexImport
      parentRoute: typeof AuthSignInImport
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexImport
      parentRoute: typeof AuthSignUpImport
    }
  }
}

// Create and export the route tree

interface AuthSignInRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInRouteChildren: AuthSignInRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInRouteWithChildren = AuthSignInRoute._addFileChildren(
  AuthSignInRouteChildren,
)

interface AuthSignUpRouteChildren {
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthSignUpRouteChildren: AuthSignUpRouteChildren = {
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthSignUpRouteWithChildren = AuthSignUpRoute._addFileChildren(
  AuthSignUpRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/harmony-palette': typeof HarmonyPaletteIndexRoute
  '/image-picker': typeof ImagePickerIndexRoute
  '/my-palettes': typeof MyPalettesIndexRoute
  '/random-palette': typeof RandomPaletteIndexRoute
  '/scale-palette': typeof ScalePaletteIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harmony-palette': typeof HarmonyPaletteIndexRoute
  '/image-picker': typeof ImagePickerIndexRoute
  '/my-palettes': typeof MyPalettesIndexRoute
  '/random-palette': typeof RandomPaletteIndexRoute
  '/scale-palette': typeof ScalePaletteIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/harmony-palette/': typeof HarmonyPaletteIndexRoute
  '/image-picker/': typeof ImagePickerIndexRoute
  '/my-palettes/': typeof MyPalettesIndexRoute
  '/random-palette/': typeof RandomPaletteIndexRoute
  '/scale-palette/': typeof ScalePaletteIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/harmony-palette'
    | '/image-picker'
    | '/my-palettes'
    | '/random-palette'
    | '/scale-palette'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/harmony-palette'
    | '/image-picker'
    | '/my-palettes'
    | '/random-palette'
    | '/scale-palette'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/harmony-palette/'
    | '/image-picker/'
    | '/my-palettes/'
    | '/random-palette/'
    | '/scale-palette/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRouteWithChildren
  HarmonyPaletteIndexRoute: typeof HarmonyPaletteIndexRoute
  ImagePickerIndexRoute: typeof ImagePickerIndexRoute
  MyPalettesIndexRoute: typeof MyPalettesIndexRoute
  RandomPaletteIndexRoute: typeof RandomPaletteIndexRoute
  ScalePaletteIndexRoute: typeof ScalePaletteIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRouteWithChildren,
  HarmonyPaletteIndexRoute: HarmonyPaletteIndexRoute,
  ImagePickerIndexRoute: ImagePickerIndexRoute,
  MyPalettesIndexRoute: MyPalettesIndexRoute,
  RandomPaletteIndexRoute: RandomPaletteIndexRoute,
  ScalePaletteIndexRoute: ScalePaletteIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/sign-in",
        "/auth/sign-up",
        "/harmony-palette/",
        "/image-picker/",
        "/my-palettes/",
        "/random-palette/",
        "/scale-palette/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.ts",
      "children": [
        "/auth/sign-in/"
      ]
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.ts",
      "children": [
        "/auth/sign-up/"
      ]
    },
    "/harmony-palette/": {
      "filePath": "harmony-palette/index.tsx"
    },
    "/image-picker/": {
      "filePath": "image-picker/index.tsx"
    },
    "/my-palettes/": {
      "filePath": "my-palettes/index.tsx"
    },
    "/random-palette/": {
      "filePath": "random-palette/index.tsx"
    },
    "/scale-palette/": {
      "filePath": "scale-palette/index.tsx"
    },
    "/auth/sign-in/": {
      "filePath": "auth/sign-in/index.tsx",
      "parent": "/auth/sign-in"
    },
    "/auth/sign-up/": {
      "filePath": "auth/sign-up/index.tsx",
      "parent": "/auth/sign-up"
    }
  }
}
ROUTE_MANIFEST_END */
